<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'app_job' => [[], ['_controller' => 'App\\Controller\\JobController::index'], [], [['text', '/job']], [], []],
    'job_add' => [[], ['_controller' => 'App\\Controller\\JobController::add_job'], [], [['text', '/add_job']], [], []],
    'app_reporting' => [[], ['_controller' => 'App\\Controller\\PropertyController::index'], [], [['text', '/property']], [], []],
];
